POST {{API_URL}}/api/v1/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY1MjEzOTYzN30.lyXpNZsvMeuAA70MDUY4UywRcAjYKUiCKbCJdIpbz0Q

{
  "name": "Category 1",
  "image": "https://placeimg.com/640/480/"
}
